### ISSUE TITLE
How to manage target black only for image link?

### ISSUE THREAD

**Issue by rvpatel** [mukto90/mdc-target-blank#1]
How to manage target black only for image link using this function?

`<a title="test" href="http://199.256.50.458/test/?attachment_id=1829"><img class="attachment-thumbnail" src="http://199.256.50.458/test/wp-content/uploads/2009/05/Brenda-test.jpg"></a>`

**Comment by mukto90** [comment]
You cannot do this. Because, there is nothing called "image link". What this plugin does is to replace `<a` with `<a target="_blank"` in the post content.
